---
certbot_auto_renew: true
certbot_auto_renew_user: root
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: --quiet --no-self-upgrade --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"
certbot_admin_email: infrastructure-team@studentrobotics.org
certbot_create_if_missing: true
certbot_create_standalone_stop_services:
 - nginx


# Override serving of the root url to be the competition mode homepage instead
# of the normal one.
enable_competition_homepage: false


firewall_allowed_tcp_ports:
 - "22"
 - "80"
 - "443"
firewall_ip6_additional_rules:
 # Allow Mythic's managed services access
 - ip6tables -A INPUT -p tcp --dport 4949 -s 2a00:1098:0:80:1000::100 -j ACCEPT
firewall_log_dropped_packets: false


# For now all these users get sudo. If we start adding other users we should
# probably break this into groups and do finer grained permissions.
users:
 - jhoward
 - jsedensmith
 - plaw

secrets_dir: /srv/secrets
