- name: Common baseline
  hosts: all
  roles:
    # Users first, so that when root SSH is disabled we still have a way to
    # access the machine.
    - users
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.security
    - bee

- name: Web proxies
  hosts: webproxies
  roles:
    - srobo-nginx
