- name: Install virtualenv system dependencies
  apt:
    pkg:
      - python3-virtualenv
      - python3-wheel

- name: Create install directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: www-data
    mode: "755"

- name: Download
  git:
    repo: https://github.com/srobo/helpdesk-system
    dest: "{{ install_dir }}"
    force: true
    version: sr2024  # TODO: Pin to commit
  notify:
    Restart helpdesk-system
  register: helpdesk_system_repo
  become_user: www-data

# NOTE: It is expected this configuration won't work as-is
- name: Create configuration if it doesn't exist
  copy:
    force: false
    remote_src: true
    src: "{{ install_dir }}/helpdesk/helpdesk/configuration.example.py"
    dest: "{{ install_dir }}/helpdesk/helpdesk/configuration.py"
    mode: "0600"
    owner: www-data
  notify:
    Restart helpdesk-system

- name: Install virtual environment
  pip:
    virtualenv: "{{ venv_dir }}"
    requirements: "{{ install_dir }}/requirements.txt"
  notify:
    Restart helpdesk-system
  become_user: www-data
  when: helpdesk_system_repo.changed  # noqa: no-handler - Use a handler to ensure execution order

- name: Install deploy requirements
  pip:
    # Latest at the time of writing. Don't actually care about the version,
    # only that we pin it for stability.
    name: gunicorn==21.2.0
    virtualenv: "{{ venv_dir }}"
  notify:
    Restart helpdesk-system
  become_user: www-data

- name: Install systemd service
  template:
    src: helpdesk-system.service
    dest: /etc/systemd/system/helpdesk-system.service
    mode: "0644"
  notify:
    Restart helpdesk-system

- name: Install nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/locations-enabled/helpdesk-system
    mode: "0644"
  notify:
    Reload nginx

- name: Run migrations  # noqa: no-changed-when - We want to always run this (it handles its own idempotency)
  community.general.django_manage:
    command: migrate --noinput -v0
    app_path: "{{ install_dir }}/helpdesk"
    virtualenv: "{{ venv_dir }}"
  become_user: www-data
  when: helpdesk_system_repo.changed  # noqa: no-handler - Use a handler to ensure execution order

- name: Collect static  # noqa: no-changed-when - We want to always run this (it handles its own idempotency)
  community.general.django_manage:
    command: collectstatic --noinput -v0
    app_path: "{{ install_dir }}/helpdesk"
    virtualenv: "{{ venv_dir }}"
  become_user: www-data
  when: helpdesk_system_repo.changed  # noqa: no-handler - Use a handler to ensure execution order

- name: Enable service
  service:
    name: helpdesk-system
    state: started
    enabled: true
