---
- name: Install nginx
  apt:
    pkg: nginx
    update_cache: true
    state: latest  # noqa: package-latest
    cache_valid_time: 86400

- name: Install ssl-cert (for TLS certificates in development)
  apt:
    pkg: ssl-cert
  when: not certbot_create_if_missing

- name: Create .well-known directory
  file:
    path: /var/www/.well-known
    state: directory
    owner: www-data
    mode: "755"
  notify:
    Reload nginx

- name: Copy .well-known/mta-sts.txt
  copy:
    src: files/well-known-mta-sts.txt
    dest: /var/www/.well-known/mta-sts.txt
    mode: "0644"
  notify:
    Reload nginx

- name: Copy dhparam.txt
  copy:
    src: files/dhparam.txt
    dest: /etc/nginx/dhparam.txt
    mode: "0644"
  notify:
    Reload nginx

- name: Copy our configuration
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    validate: /usr/sbin/nginx -t -c %s
  notify:
    Reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
