- name: Install motd
  copy:
    src: files/bee.txt
    dest: /etc/motd
    mode: "644"

# https://blog.ktz.me/remove-ubuntu-motd-spam-at-login/
- name: Remove ubuntu motd spam
  file:
    path: /etc/update-motd.d/{{ item }}
    state: absent
  loop:
    - 80-livepatch
    - 95-hwe-eol
    - 10-help-text
    - 50-motd-news
